version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins_php
    ports:
      - 8080:8080
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net

  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: Server
    networks:
      - net

networks:
  net:
